import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import { env } from "@/env";
import { Providers } from "@/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Using the Next.js Metadata API causes these tags to get moved to the body which breaks the AppBridge */}
        <meta
          name="shopify-api-key"
          content={env.NEXT_PUBLIC_SHOPIFY_API_KEY}
        />
        <meta
          name="shopify-app-origins"
          content={env.NEXT_PUBLIC_SHOPIFY_APP_URL}
        />

        {/* Next.js <Script /> tag uses async which breaks the AppBridge */}
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="https://cdn.shopify.com/shopifycloud/app-bridge.js" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
